server:
  port: ${PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:1}
  jpa:
    properties:
      hibernate:
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
        search:
          enabled: false

hapi:
  fhir:
    fhir_version: R4
    cr:
      enabled: true
    cdshooks:
      enabled: false
